name: Release NovaStream

on:
  push:
    tags:
      - 'v*'

jobs:
  release-macos:
    name: Build & Release macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install UPX
        run: brew install upx || true
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build macOS binary
        run: |
          pyinstaller --clean --strip --windowed --onefile --name novastream \
            --exclude-module seleniumwire \
            --exclude-module selenium \
            --exclude-module webdriver_manager \
            --add-data "src/icon.png:src" \
            src/gui.py
      - name: Zip macOS binary
        run: zip -j novastream-macos-${{ github.ref_name }}.zip dist/novastream
      - name: Publish macOS asset
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: novastream-macos-${{ github.ref_name }}.zip
          name: novastream-macos-${{ github.ref_name }}.zip
          draft: false
          prerelease: false

  release-windows:
    name: Build & Release Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build Windows binary
        shell: cmd
        run: |
          pyinstaller --clean --strip --windowed --onefile --name novastream.exe ^
            --exclude-module seleniumwire ^
            --exclude-module selenium ^
            --exclude-module webdriver_manager ^
            --add-data "src\\icon.png;src" ^
            src\\gui.py
      - name: Zip Windows binary
        run: powershell -Command "Compress-Archive -Path dist\novastream.exe -DestinationPath novastream-windows-${{ github.ref_name }}.zip"
      - name: Publish Windows asset
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: novastream-windows-${{ github.ref_name }}.zip
          name: novastream-windows-${{ github.ref_name }}.zip
          draft: false
          prerelease: false

  release-linux:
    name: Build & Release Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl zip libgtk-3-dev libgl1-mesa-dev libglib2.0-dev
          pip install pyinstaller
      - name: Build Linux binary
        run: |
          pyinstaller --clean --strip --windowed --onefile --name novastream \
            --exclude-module seleniumwire \
            --exclude-module selenium \
            --exclude-module webdriver_manager \
            --add-data "src/icon.png:src" \
            src/gui.py
      - name: Zip Linux binary
        run: zip -j novastream-linux-${{ github.ref_name }}.zip dist/novastream
      - name: Publish Linux asset
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: novastream-linux-${{ github.ref_name }}.zip
          name: novastream-linux-${{ github.ref_name }}.zip
          draft: false
          prerelease: false 